version: 0.2

env:
  variables:
    CODE_SRC_DIR: "."
  exported-variables:
    - DiffMessage
    - DiffValue
    - DiffPercentage

phases:
  install:
    commands:
      - "curl -O -L https://infracost.io/downloads/v0.10/infracost-linux-amd64.tar.gz"
      - tar xzf infracost-linux-amd64.tar.gz -C /tmp
      - mv /tmp/infracost-linux-amd64 /usr/local/bin/infracost
      - rm -rf infracost-linux-amd64.tar.gz
      - infracost --version
  build:
    commands:
      - "cd ${CODEBUILD_SRC_DIR_TerraformPlan}/${CODE_SRC_DIR}"
      - infracost breakdown --path tfapply.json --format json --out-file breakdown.json
      - cat breakdown.json
      - infracost output --path breakdown.json --format table
      - infracost output --path breakdown.json --format diff
      - "export DiffMessage=`infracost output --path breakdown.json --format diff`"
      - "export DiffValue=`jq -r '.diffTotalMonthlyCost' breakdown.json`"
      - echo ${DiffMessage}
      - echo ${DiffValue}


artifacts:
  files:
    - "**/*"
