version: 0.2

env:
  variables:
    CODE_SRC_DIR: "."
  exported-variables:
    - DiffMessage
    - PastTotalMonthlyCost
    - TotalMonthlyCost
    - DiffTotalMonthlyCost

phases:
  install:
    commands:
      - "curl -O -L https://infracost.io/downloads/v0.10/infracost-linux-amd64.tar.gz"
      - tar xzf infracost-linux-amd64.tar.gz -C /tmp
      - mv /tmp/infracost-linux-amd64 /usr/local/bin/infracost
      - rm -rf infracost-linux-amd64.tar.gz
      - infracost --version
  build:
    commands:
      - "cd ${CODEBUILD_SRC_DIR_TerraformPlan}/${CODE_SRC_DIR}"
      - infracost breakdown --usage-file infracost-usage.yml --path terraform/tfapply.json --format json --out-file breakdown.json
      - cat breakdown.json
      - infracost output --path breakdown.json --format table
      - infracost output --path breakdown.json --format diff
      - "export DiffMessage=`infracost output --path breakdown.json --format diff`"
      - "export DiffTotalMonthlyCost=`jq -r '.diffTotalMonthlyCost' breakdown.json`"
      - "export PastTotalMonthlyCost=`jq -r '.pastTotalMonthlyCost' breakdown.json`"
      - "export TotalMonthlyCost=`jq -r '.totalMonthlyCost' breakdown.json`"
      - echo ${DiffMessage}
      - echo ${TotalMonthlyCost}
      - echo ${PastTotalMonthlyCost}
      - echo ${DiffTotalMonthlyCost}

artifacts:
  files:
    - "**/*"
